static const char led_web_css[] =
"/* the LED's own rules, travelling with the LED */\n"
".node-led {\n"
"  width: 10px;\n"
"  height: 10px;\n"
"  border-radius: 50%;\n"
"  background: #555;\n"
"  flex: 0 0 auto;\n"
"}\n"
".node-led.state-0 { background: #666; }\n"
".node-led.state-1 { background: #e6c66b; }\n"
".node-led.state-2 { background: #6be69a; box-shadow: 0 0 6px #6be69a; }\n"
"\n"
"/* stretched when it is the wireable cell of a row */\n"
".wireable > .node-led {\n"
"  flex: 1 1 auto;\n"
"  min-width: 0;\n"
"}\n"
;
